### ISSUE TITLE
Option `withid` doest not seem to work

### ISSUE THREAD

**Issue by ebousse** [correctexam/latextemplate#1]
The option `withid` is supposed to trigger the display of a form element to write the student ID, but currently it seems to not do anything when enabled.

To reproduce, simply compile `exam-example.tex` (which uses this option):

```
latexmk -pdf exam-example.tex
```

And we get this result, without the student ID form:

![image](https://github.com/correctexam/latextemplate/assets/5868014/457586f0-0af1-457a-a39a-c2ef6adb6884)

I tried debugging the issue, but strangely whatever I try the boolean `@headerWithID` remains at `false`.

**Comment by arnobl** [comment]
Fixed
